# Generated by Django 2.2 on 2020-05-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipeYield', models.CharField(max_length=20)),
                ('isVegetarian', models.BooleanField()),
                ('isVegan', models.BooleanField()),
                ('prepTime', models.CharField(max_length=15)),
                ('cookTime', models.CharField(max_length=15)),
                ('cookingMethod', models.CharField(max_length=15)),
                ('temp', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
